config/routes.rb
Rails.application.routes.draw do

  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :title, presence: true

  has_attached_file :photo_file_name, :styles => {:medium => "400x200>", :thumb => "200x100>", :default_url => ""}
  validates_attachment_content_type :photo_file_name, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def create
    @photo = Photo.new(params_photo)
    if @photo.save
      redirect_to photos_path, :notice => "Upload image #{@photo.title} success"
    else
      render "new", :error => "Upload image #{@photo.title} failed"
    end
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(params_photo)
      redirect_to photos_path, :notice => "Update image #{@photo.title} success"
    else
      render "new", :error => "Update image #{@photo.title} failed"
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      redirect_to photos_path, :notice => "Delete photo #{@photo.title} success"
    else
      redirect_to photos_path, :error => "Delete photo #{@photo.title} failed"
    end
  end

  private
    def params_photo
      params.require(:photo).permit(:title, :photo_file_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Gallery", photos_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Tambah", new_photo_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @photo do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photo_file_name %>
    <%= f.file_field :photo_file_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h2>Edit Photo</h2>
<b>Picture now</b><br>
<%= image_tag @photo.photo_file_name.url %>
<%= render "form" %>

app/views/photos/index.html.erb
<h2>Welcome</h2>

<div class="row">
  <% @photos.each do |photo| %>
    <div class="col-lg-3">
      <%= link_to (image_tag photo.photo_file_name.url(:medium)), photo_path(photo) %><br>
      <b><%= photo.title %></b><br>
      <%= link_to "Edit", edit_photo_path(photo) %> |
      <%= link_to "Delete", photo_path(photo), :method => :delete, :data => {confirm: "Are you sure want to delete this file?"} %>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<h2>Add New Photo</h2>
<%= render "form" %>

app/views/photos/show.html.erb
<h2><%= @photo.title %></h2>
<%= link_to (image_tag @photo.photo_file_name.url()), photo_path(@photo) %><br>
<%= link_to "Edit", edit_photo_path(@photo) %> |
<%= link_to "Delete", photo_path(@photo), :method => :delete, :data => {confirm: "Are you sure want to delete this file?"} %>